apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: viktolearn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata: 
      labels:
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_DB
              value: viktolearn
            - name: POSTGRES_USER
              value: viktolearn
            - name: POSTGRES_PASSWORD
              value: viktolearn