namespace:
  create: true
  name: viktolearn-helm

api:
  replicaCount: 1

  image:
    repository: ghcr.io/viktoriia-ds/viktolearn-devops-platform
    tag: "f8366358ca20aff2b2b825337db026543e949ab4"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
      ephemeralStorage: "100Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
      ephemeralStorage: "500Mi"

postgres:
  replicaCount: 1

  image:
    repository: postgres
    tag: "17"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5432

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
      ephemeralStorage: "100Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
      ephemeralStorage: "500Mi"

  database: viktolearn
  user: viktolearn
  password: viktolearn

  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "8-alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
      ephemeralStorage: "50Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
      ephemeralStorage: "250Mi"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20

  startup:
    path: /health
    failureThreshold: 30
    periodSeconds: 5

resourceQuota:
  enabled: true

  hard:
    requestsCpu: "1"
    requestsMemory: "1Gi"
    limitsCpu: "3"
    limitsMemory: "3Gi"
    pods: "10"
    persistentVolumeClaims: "5"
    requestsStorage: "10Gi"

networkPolicy:
  enabled: true
