apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: viktolearn
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Viktoriia-DS/ViktoLearn-devops-platform.git
    targetRevision: main
    path: helm/viktolearn

  destination:
    server: https://kubernetes.default.svc
    namespace: viktolearn-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
