apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: {{ .Values.namespace.name }}

spec:
  replicas: {{ .Values.api.replicaCount }}

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api

          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu | quote }}
              memory: {{ .Values.api.resources.requests.memory | quote }}
            limits: 
              cpu: {{ .Values.api.resources.limits.cpu | quote }}
              memory: {{ .Values.api.resources.limits.memory | quote }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.api.service.port }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}

          env:
            - name: DB_HOST
              valueFrom: 
                configMapKeyRef:
                  name: viktolearn-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: viktolearn-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom: 
                configMapKeyRef:
                  name: viktolearn-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: viktolearn-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viktolearn-secret
                  key: DB_PASSWORD

            - name: REDIS_HOST
              valueFrom: 
                configMapKeyRef:
                  name: viktolearn-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom: 
                configMapKeyRef:
                  name: viktolearn-config
                  key: REDIS_PORT