apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: viktolearn-route
  namespace: {{ .Values.namespace.name }}

spec:
  parentRefs:
    - name: viktolearn-gateway

  hostnames:
    - viktolearn.local

  rules:
    # API traffic: /api/courses -> /courses
    - matches:
        - path:
            type: PathPrefix
            value: /api

      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /

      backendRefs:
        - name: api
          port: {{ .Values.api.service.port }}

    # All other traffic -> React frontend
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: frontend
          port: {{ .Values.frontend.service.port }}
