apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}

spec:
  replicas: {{ .Values.postgres.replicaCount }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      securityContext:
        runAsNonRoot: {{ .Values.postgres.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.postgres.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.postgres.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.postgres.podSecurityContext.fsGroup }}

      containers:
        - name: postgres

          securityContext:
            allowPrivilegeEscalation: {{ .Values.postgres.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.postgres.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
                {{- toYaml .Values.postgres.securityContext.capabilities.drop | nindent 16 }}

          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.postgres.service.port }}

          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
              memory: {{ .Values.postgres.resources.requests.memory | quote }}
              ephemeral-storage: {{ .Values.postgres.resources.requests.ephemeralStorage | quote }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu | quote }}
              memory: {{ .Values.postgres.resources.limits.memory | quote }}
              ephemeral-storage: {{ .Values.postgres.resources.limits.ephemeralStorage | quote }}

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            - name: postgres-run
              mountPath: /var/run/postgresql

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: viktolearn-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: viktolearn-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viktolearn-secret
                  key: DB_PASSWORD

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

        - name: postgres-run
          emptyDir: {}