apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: {{ .Values.namespace.name }}

spec:
  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      securityContext:
        runAsNonRoot: {{ .Values.redis.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.redis.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.redis.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.redis.podSecurityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.redis.podSecurityContext.seccompProfile.type }}

      containers:
        - name: redis

          securityContext:
            allowPrivilegeEscalation: {{ .Values.redis.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.redis.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
                {{- toYaml .Values.redis.securityContext.capabilities.drop | nindent 16 }}

          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.redis.service.port }}

          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}
              ephemeral-storage: {{ .Values.redis.resources.requests.ephemeralStorage | quote }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
              memory: {{ .Values.redis.resources.limits.memory | quote }}
              ephemeral-storage: {{ .Values.redis.resources.limits.ephemeralStorage | quote }}

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          volumeMounts:
            - name: redis-data
              mountPath: /data

      volumes:
        - name: redis-data
          emptyDir: {}
