{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "viktolearn.fullname" . }}-quota
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "viktolearn.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.hard.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.hard.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.hard.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.hard.limitsMemory | quote }}
    pods: {{ .Values.resourceQuota.hard.pods | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.hard.persistentVolumeClaims | quote }}
    requests.storage: {{ .Values.resourceQuota.hard.requestsStorage | quote }}
{{- end }}
