apiVersion: v1
kind: Secret

metadata: 
    name: viktolearn-secret
    namespace: {{ .Values.namespace.name }}

type: Opaque

stringData:
    DB_USER: {{ .Values.postgres.user | quote }}
    DB_PASSWORD: {{ .Values.postgres.password | quote }} 